export {
  AvisoGate,
  AvatarAutor,
  BotaoPrimario,
  BotaoSecundario,
  CabecalhoConvidado,
  CabecalhoPublicacao,
  CampoNome,
  ChaoConvidado,
  ColunaEntrada,
  Consentimento,
  EstadoVazio,
  FaixaMissao,
  iniciaisDoAutor,
  LinkDiscreto,
  MioloConvidado,
  PADDING_LATERAL,
  RecadoConsentimento,
  RecadoErro,
  RodapeDiscreto,
  RotuloEvento,
  RODAPE_ABAS,
  SheetBaixo,
  TextoSecundario,
  TituloGrande,
} from "@albora/ui-web";
