import type { Pack } from "./tipos";

/** O único lugar do repositório onde "noivos" pode aparecer — se vazar para core, ui-* ou schema, o guard reprova. */
export const CASAMENTO: Pack = {
  id: "casamento",
  sugereAntes: "pre-casamento",
  icone: "heart",
  ordemCriacao: 1,
  vocabulario: {
    "evento.nome": "casamento",
    "evento.descricao": "A festa inteira, do altar à última música.",
    // Frases de domínio do onboarding — o template ("Preparamos tudo pra …") é
    // produto e vive no componente; o artigo e a posse corretos vêm daqui.
    "evento.preparo": "um casamento",
    "evento.posse": "do seu casamento",
    "anfitriao.plural": "os noivos",
    "convidado.saudacao": "Que bom te ver aqui",
    "missao.titulo": "Missões da festa",
    "missao.livre": "Ou fotografe o que quiser",
    "missao.chegada": "A chegada de quem você não via há tempos",
    "missao.mesa": "A sua mesa, do jeito que ela está agora",
    "missao.danca": "Alguém dançando como se ninguém visse",
    "missao.brinde": "O brinde, no instante do brinde",
    "galeria.minhas": "Minhas fotos",
    "musica.escolha": "Escolha dos noivos",
    "telao.vazio": "As primeiras fotos aparecem aqui",
    "lugar.pergunta": "Onde na festa?",
    "interacao.aberta": "Feed liberado — veja o que rolou",
    "interacao.fechada": "Interação abre após a cerimônia",
    "interacao.fechada.agendada": "Interação abre às {hora}",
    "recado.rotulo": "Um recado dos noivos",
    "recado.exemplo":
      "Obrigado por estar com a gente hoje. Tirem fotos — as suas também são as nossas.",
    "confessionario.titulo": "Confessionário",
    "confessionario.lede": "Escolha uma pergunta e grave um vídeo curto para o álbum.",
    "confessionario.conselho": "Que conselho você dá para a vida a dois?",
    "confessionario.historia": "Conte uma história boa com os noivos.",
    "confessionario.desejo": "O que você deseja para eles daqui a dez anos?",
    "confessionario.segredo": "Um segredo engraçado que só a mesa sabe.",
    "lugar.pista": "Pista",
    "lugar.mesa": "Mesa",
    "lugar.jardim": "Jardim",
    "lugar.altar": "Altar",
    "lugar.bar": "Bar",
    "lugar.varanda": "Varanda",

    "landing.rotulo": "Fotos de festa · sem app",
    "landing.titulo": "Viva a festa.",
    "landing.titulo.destaque": "Reúna as fotos de todos.",
    "landing.lede":
      "Um álbum coletivo para casamentos, aniversários e outras festas. Seus convidados enviam fotos por QR Code, direto do celular.",
    "landing.cta": "Testar meu álbum",
    "landing.exemplo.nome": "ANA & JOÃO",
    "landing.demo.placeholder": "Ex.: Casamento da Bia e do Pedro",
    "landing.demo.album.sub": "Um dia. Muitos olhares.",
    "landing.pacote.exemplos":
      "Noivado, chá e casamento. Ou os próximos aniversários da família.",

    "reacao.estrela": "Estrela",
    "reacao.riso": "Riso",
    "reacao.choro": "Choro",
    "reacao.festa": "Festa",
    "momento.antes": "Antes de tudo",
    "momento.antes.desc": "O nervoso, o cabelo, o quarto cheio de gente.",
    "momento.cerimonia": "A cerimônia",
    "momento.cerimonia.desc": "O sim, os olhares e quem chorou primeiro.",
    "momento.recepcao": "A recepção",
    "momento.recepcao.desc": "Os abraços de quem você não via há anos.",
    "momento.coquetel": "O coquetel",
    "momento.coquetel.desc": "Conversa em pé, taça na mão, foto sem aviso.",
    "momento.jantar": "O jantar",
    "momento.jantar.desc": "Os discursos, os brindes e a mesa inteira rindo.",
    "momento.pista": "A pista",
    "momento.pista.desc": "Quando ninguém mais olha para o relógio.",
    "momento.depois": "Depois",
    "momento.depois.desc": "O salão vazio e os sapatos na mão.",
  },
  reacoes: [
    { id: "estrela", chaveTitulo: "reacao.estrela" },
    { id: "riso", chaveTitulo: "reacao.riso" },
    { id: "choro", chaveTitulo: "reacao.choro" },
    { id: "festa", chaveTitulo: "reacao.festa" },
  ],
  momentos: [
    { id: "antes", chaveTitulo: "momento.antes", chaveDesc: "momento.antes.desc" },
    { id: "cerimonia", chaveTitulo: "momento.cerimonia", chaveDesc: "momento.cerimonia.desc" },
    { id: "recepcao", chaveTitulo: "momento.recepcao", chaveDesc: "momento.recepcao.desc" },
    { id: "coquetel", chaveTitulo: "momento.coquetel", chaveDesc: "momento.coquetel.desc" },
    { id: "jantar", chaveTitulo: "momento.jantar", chaveDesc: "momento.jantar.desc" },
    { id: "pista", chaveTitulo: "momento.pista", chaveDesc: "momento.pista.desc" },
    { id: "depois", chaveTitulo: "momento.depois", chaveDesc: "momento.depois.desc" },
  ],
  missoes: [
    { id: "chegada", chaveTitulo: "missao.chegada", ordem: 1 },
    { id: "mesa", chaveTitulo: "missao.mesa", ordem: 2 },
    { id: "danca", chaveTitulo: "missao.danca", ordem: 3 },
    { id: "brinde", chaveTitulo: "missao.brinde", ordem: 4 },
  ],
  confessionario: [
    { id: "conselho", chaveTitulo: "confessionario.conselho" },
    { id: "historia", chaveTitulo: "confessionario.historia" },
    { id: "desejo", chaveTitulo: "confessionario.desejo" },
    { id: "segredo", chaveTitulo: "confessionario.segredo" },
  ],
  lugares: [
    { id: "pista", chaveTitulo: "lugar.pista" },
    { id: "mesa", chaveTitulo: "lugar.mesa" },
    { id: "jardim", chaveTitulo: "lugar.jardim" },
    { id: "altar", chaveTitulo: "lugar.altar" },
    { id: "bar", chaveTitulo: "lugar.bar" },
    { id: "varanda", chaveTitulo: "lugar.varanda" },
  ],
  tokens: {
    fontes: { titulo: "Fraunces, Georgia, serif" },
  },
};

export const WEDDING = CASAMENTO;
