import type { Pack } from "./tipos";

export const PRE_CASAMENTO: Pack = {
  id: "pre-casamento",
  vocabulario: {
    "evento.nome": "comemoração",
    "evento.descricao": "Noivado, chá de panela, despedida — as festas antes da festa.",
    "sugestao.titulo": "Entre o sim e a festa existem outras festas",
    "sugestao.lede":
      "Noivado, chá de panela, despedida, ensaio — são as mesmas pessoas, e cada uma abre um álbum. Quando chegar o casamento, os seus convidados já vão saber como funciona.",
    "sugestao.cta": "Criar álbum de uma comemoração",
    "sugestao.rotulo": "Não começa no dia do casamento",
    "sugestao.chamada": "O álbum do noivado inteiro, não só da última noite.",
    "sugestao.efeito":
      "Começar cedo tem um efeito prático: quando chega o casamento, os seus convidados já sabem como funciona — e é isso que decide quantas fotos aparecem.",
    "ocasiao.noivado": "Noivado",
    "ocasiao.noivado.quando": "12 a 18 meses antes",
    "ocasiao.cha": "Chá de panela",
    "ocasiao.cha.quando": "3 a 6 meses antes",
    "ocasiao.despedida": "Despedida",
    "ocasiao.despedida.quando": "semanas antes",
    "ocasiao.ensaio": "Ensaio",
    "ocasiao.ensaio.quando": "1 a 3 meses antes",
    "anfitriao.plural": "os noivos",
    "convidado.saudacao": "Que bom que você veio",
    "missao.titulo": "Missões da comemoração",
    "missao.livre": "Ou fotografe o que quiser",
    "missao.chegada": "Quem chegou primeiro",
    "missao.mesa": "A mesa, do jeito que ela está agora",
    "missao.presente": "O presente sendo aberto",
    "missao.brinde": "O brinde, no instante do brinde",
    "missao.risada": "Alguém rindo alto demais",
    "missao.dupla": "Os dois juntos, sem posar",
    "galeria.minhas": "Minhas fotos",
    "musica.escolha": "Escolha dos noivos",
    "telao.vazio": "As primeiras fotos aparecem aqui",
    "lugar.pergunta": "Onde na comemoração?",
    "interacao.aberta": "Feed liberado — veja o que rolou",
    "interacao.fechada": "Interação abre em breve",
    "interacao.fechada.agendada": "Interação abre às {hora}",
    "recado.rotulo": "Um recado dos noivos",
    "recado.exemplo":
      "Obrigado por vir. Tirem foto de tudo — isso aqui também é parte da história.",
    "confessionario.titulo": "Confessionário",
    "confessionario.lede": "Escolha uma pergunta e grave um vídeo curto para o álbum.",
    "confessionario.conselho": "Que conselho você dá para os dois?",
    "confessionario.historia": "Conte como você conheceu os noivos.",
    "confessionario.aposta": "Como você imagina o casamento deles?",
    "lugar.mesa": "Mesa",
    "lugar.cozinha": "Cozinha",
    "lugar.quintal": "Quintal",
    "lugar.sala": "Sala",
    "lugar.bar": "Bar",
  },
  missoes: [
    { id: "chegada", chaveTitulo: "missao.chegada", ordem: 1 },
    { id: "dupla", chaveTitulo: "missao.dupla", ordem: 2 },
    { id: "presente", chaveTitulo: "missao.presente", ordem: 3 },
    { id: "brinde", chaveTitulo: "missao.brinde", ordem: 4 },
    { id: "mesa", chaveTitulo: "missao.mesa", ordem: 5 },
    { id: "risada", chaveTitulo: "missao.risada", ordem: 6 },
  ],
  confessionario: [
    { id: "conselho", chaveTitulo: "confessionario.conselho" },
    { id: "historia", chaveTitulo: "confessionario.historia" },
    { id: "aposta", chaveTitulo: "confessionario.aposta" },
  ],
  lugares: [
    { id: "mesa", chaveTitulo: "lugar.mesa" },
    { id: "cozinha", chaveTitulo: "lugar.cozinha" },
    { id: "quintal", chaveTitulo: "lugar.quintal" },
    { id: "sala", chaveTitulo: "lugar.sala" },
    { id: "bar", chaveTitulo: "lugar.bar" },
  ],
};

export const PRE_WEDDING = PRE_CASAMENTO;
