import type { Pack } from "./tipos";

/** Dois packs existem de propósito — com um só é impossível saber se o núcleo é genérico ou se o vocabulário de casamento está grudado nele. */
export const QUINZE_ANOS: Pack = {
  id: "quinze-anos",
  vocabulario: {
    "evento.nome": "aniversário de 15 anos",
    "evento.descricao": "A entrada, a valsa e a pista até o fim.",
    "anfitriao.plural": "a aniversariante",
    "convidado.saudacao": "Chegou a hora da festa",
    "missao.titulo": "Missões da noite",
    "missao.livre": "Ou fotografe o que quiser",
    "missao.chegada": "A entrada, com a música alta",
    "missao.valsa": "A valsa, de onde você estiver",
    "missao.pista": "A pista quando ela enche",
    "galeria.minhas": "Minhas fotos",
    "musica.escolha": "Escolha da aniversariante",
    "telao.vazio": "As primeiras fotos aparecem aqui",
    "lugar.pergunta": "Onde na festa?",
    "interacao.aberta": "Feed liberado — veja o que rolou",
    "interacao.fechada": "Interação abre depois da entrada",
    "interacao.fechada.agendada": "Interação abre às {hora}",
    "recado.rotulo": "Um recado da aniversariante",
    "recado.exemplo":
      "Obrigada por vir. Tirem fotos — eu quero ver a festa pelos olhos de vocês.",
    "confessionario.titulo": "Confessionário",
    "confessionario.lede": "Escolha uma pergunta e grave um vídeo curto para o álbum.",
    "confessionario.conselho": "Que conselho você dá para os 15?",
    "confessionario.historia": "Conte uma história boa com a aniversariante.",
    "confessionario.desejo": "O que você deseja para ela daqui a dez anos?",
    "lugar.pista": "Pista",
    "lugar.mesa": "Mesa",
    "lugar.jardim": "Jardim",
    "lugar.bar": "Bar",
    "lugar.varanda": "Varanda",

    "landing.rotulo": "Fotos de festa · sem app",
    "landing.titulo": "As fotos dos seus 15 anos,",
    "landing.titulo.destaque": "tiradas por quem viveu eles.",
    "landing.lede":
      "Um QR na mesa. Sem app, sem login, sem baixar nada. No dia seguinte, você acorda com centenas de fotos que ninguém contratou pra tirar.",
    "landing.cta": "Criar meu evento",

    "reacao.estrela": "Estrela",
    "reacao.riso": "Riso",
    "reacao.choro": "Choro",
    "reacao.festa": "Festa",
    "momento.antes": "Antes de descer",
    "momento.antes.desc": "O espelho, o vestido e as amigas em volta.",
    "momento.entrada": "A entrada",
    "momento.entrada.desc": "A música alta, a escada e o salão inteiro de pé.",
    "momento.valsa": "A valsa",
    "momento.valsa.desc": "Com o pai, com os padrinhos, com quem ela quiser.",
    "momento.jantar": "O jantar",
    "momento.jantar.desc": "Os discursos e a mesa inteira rindo.",
    "momento.pista": "A pista",
    "momento.pista.desc": "Quando ninguém mais olha para o relógio.",
    "momento.depois": "Depois",
    "momento.depois.desc": "O salão vazio e os sapatos na mão.",
  },
  reacoes: [
    { id: "estrela", chaveTitulo: "reacao.estrela" },
    { id: "riso", chaveTitulo: "reacao.riso" },
    { id: "choro", chaveTitulo: "reacao.choro" },
    { id: "festa", chaveTitulo: "reacao.festa" },
  ],
  momentos: [
    { id: "antes", chaveTitulo: "momento.antes", chaveDesc: "momento.antes.desc" },
    { id: "entrada", chaveTitulo: "momento.entrada", chaveDesc: "momento.entrada.desc" },
    { id: "valsa", chaveTitulo: "momento.valsa", chaveDesc: "momento.valsa.desc" },
    { id: "jantar", chaveTitulo: "momento.jantar", chaveDesc: "momento.jantar.desc" },
    { id: "pista", chaveTitulo: "momento.pista", chaveDesc: "momento.pista.desc" },
    { id: "depois", chaveTitulo: "momento.depois", chaveDesc: "momento.depois.desc" },
  ],
  missoes: [
    { id: "chegada", chaveTitulo: "missao.chegada", ordem: 1 },
    { id: "valsa", chaveTitulo: "missao.valsa", ordem: 2 },
    { id: "pista", chaveTitulo: "missao.pista", ordem: 3 },
  ],
  confessionario: [
    { id: "conselho", chaveTitulo: "confessionario.conselho" },
    { id: "historia", chaveTitulo: "confessionario.historia" },
    { id: "desejo", chaveTitulo: "confessionario.desejo" },
  ],
  lugares: [
    { id: "pista", chaveTitulo: "lugar.pista" },
    { id: "mesa", chaveTitulo: "lugar.mesa" },
    { id: "jardim", chaveTitulo: "lugar.jardim" },
    { id: "bar", chaveTitulo: "lugar.bar" },
    { id: "varanda", chaveTitulo: "lugar.varanda" },
  ],
};

export const FIFTEEN_YEARS = QUINZE_ANOS;
