export {
  signPut,
  signGet,
  inspectObject,
  streamObject,
  readThumb,
  deleteObject,
  bufferObject,
  rangeDoPrefixoMagic,
  metadadosDaInspecao,
  assinarPut,
  assinarGet,
  inspecionarObjeto,
  lerThumb,
  type ObjectMetadata,
  type MetadadosObjeto,
} from "./r2-client";
